export const siteConfig = {
  name: "Ella Majkic",
  title: "UBC Engineering Physics Student",
  description: "Portfolio website of Ella Majkic",
  accentColor: "#B3E6F9",
  social: {
    email: "ellamaj8@gmail.com",
    linkedin: "https://www.linkedin.com/in/ella-majkic-951527289/",
    github: "https://github.com/emajkic",
  },
  aboutMe1: "I am a third-year student at the University of British Columbia majoring in Engineering Physics with a minor in Honours Mathematics. I am passionate about using machine learning, simulations, applied mathematics, software development, electronics, and physics in real-world contexts.",
  aboutMe2: "I am motivated by problems that require both analytical thinking and hands-on implementation. Whether it’s designing control systems, training models for robotic decision-making, or translating physical models into working code, I enjoy building things that connect theory to practice.",
  skills: ["Python", "Git", "Java", "Electronics", "C++", "Linux", "Bash Shell", "KiCAD", "ROOT", "ROS", "MATLAB", "Tensorflow", "Data Analysis", "CMake", "GDB", "Simulations"],
  projects: [
    {
      slug: "machine-learning-project",
      img1: "/ml3.png",
      img2: "/mfig8.png",
      img3: "/ml2.png",
      name: "ROS Machine Learning Project",
      description:
        "Applied machine learning, computer vision, and software techniques to develop and train multiple neural networks from scratch to allow a robot to autonomously drive through and solve a puzzle in ROS simulation. Achieved perfect score and 2nd place in ENPH 353 course competition.",
      skills: ["CNN", "YOLOv8", "OpenCV", "Imitation Learning", "ROS", "Python", "Linux"],
      link: "https://github.com/avi-guha/ENPH-353-COMPETITION",
      link_name: "Github Repo",
    },
    {
      slug: "robot-summer",
      img1: "/robot1.png",
      img2: "/robot2.jpg",
      img3: "/robot3.jpg",
      name: "Autonomous Competition Robot",
      description:
        "Designed, prototyped, and built an autonomous robot to participate in ENPH 253 course competition, integrating electrical, mechanical, and software modules.",
      skills: ["Robotics", "Circuit Design", "C++", "Soldering", "Software", "Prototyping"],
      link_name: "Github Repo",
      link: "https://github.com/emajkic/ENPH_253_Robot",
    },
    {
      img1: "/motor1.jpg",
      img2: "/motor3.jpg",
      img3: "/motor2.jpg",
      slug: "motor-project",
      name: "PID Motor Controller",
      description:
        "Built a circuit capable of setting and actively controlling the speed of an electric motor using PI control in hardware.",
      skills: ["Digital Logic", "Electrical Design", "Prototyping", "DAC", "Counters"],
    },
    {
      img1: "/java1.png",
      img2: "/java2.png",
      img3: "/java3.png",
      slug: "matlab-project",
      name: "PDE Solution Visualizer",
      description:
        "Programmed an interactive partial differential equation solution visualizer using MATLAB, incorporating spatial/temporal boundary conditions and source term inputs.",
      skills: ["MATLAB", "Simulation", "PDEs", "Finite Difference Methods"],
    },
    
  ],
  experience: [
    {
      slug: "triumf-experience",
      company: "TRIUMF Particle Accelerator",
      position: "Research Assistant - PIONEER Experiment",
      dateRange: "Jan 2025 - May 2025",
      description: "Worked with purity monitor assembly for rare pion decay collaboration, PIONEER. Modelled precise electron drift simulations using physics software; designed and built a vacuum system for first-ever device experimental tests.",
      pdf1: "/final_poster.pdf",
      pdf2: "/final_report.pdf",
      img1_1: "/sim2.png",
      img1_2: "/sim1.png",
      img1_3: "/sim3.jpg",
      img2_1: "/vac1.jpg",
      img2_2: "/vac2.jpg",
      img2_3: "/vac3.jpg",
      img3_1: "/test1.jpg",
      img3_2: "/test2.png",
      img3_3: "/test3.jpg",
      link_video: "https://www.youtube.com/watch?v=ad_hZ0_KblQ&t=360s",
      bullets: [
        "Worked on Purity Monitor Assembly (PUMA) instrument for a rare pion decay experiment (PIONEER)",
        "Developed physics simulations of particle behaviour in PUMA",
        "Designed and assembled a vacuum system for PUMA testing",
      ],
    },
    {
      slug: "ubc-rocket",
      company: "UBC Rocket",
      position: "Hardware Engineer - Avionics Subteam",
      dateRange: "Jan 2026 - Present",
      description: "Developed and tested hardware, firmware, and embedded systems for single-stage 30km altitude competition rocket,",
      img1_1: "/rocket1.jpeg",
      img1_2: "/rocket2.jpeg",
      img1_3: "/rocket3.jpeg",
      bullets: [
        "Worked on Purity Monitor Assembly (PUMA) instrument for a rare pion decay experiment (PIONEER)",
        "Developed physics simulations of particle behaviour in PUMA",
        "Designed and assembled a vacuum system for PUMA testing",
      ],
    },
    {
      slug: "opbots-experience",
      company: "UBC Open Robotics Design Team",
      position: "Software Engineer - Navigation Subteam",
      dateRange: "Sept 2023 - May 2025",
      description: "Developed ROS-based autonomous navigation in Python for international RoboCup@Home competition service robot.",
      img1_1: "/ros2.jpg",
      img1_2: "/ros1.png",
      img1_3: "/ros3.png",
      img2_1: "/chass1.jpg",
      img2_2: "/chass2.jpg",
      img2_3: "/chass3.jpg",
      bullets: [
        "Developed Python scripts to program autonomous navigation of service robot for international RoboCup@Home competition",
        "Worked with ROS (Robot Operating System) in Linux Ubuntu 20.04 distribution",
        "Collaborated with large student team to achieve project goals",
      ],
    }, 
  ],
  education: [
    {
      school: "Major in Engineering Physics, Minor in Honours Math - University of British Columbia",
      degree: "Bachelor of Applied Science",
      dateRange: "2023 - Present",
      achievements: [
        "2025: Eric P. Newell Award in Engineering",
        "2024: Trek Excellence Scholarship - Awarded to top 5% of students in undergrad",
        "2023-2025: Dean's Scholar, Dean's List",
      ],
      courses: [
        "Machine Learning Project (ENPH 353)",
        "Digital Systems and Microcomputers (CPEN 312)",
        "Applied Probability and Stochastic Processes (MATH 318)",
        "Data Structures and Algorithms (CPEN 211)",
        "Applied Linear Algrebra (MATH 307)",
        "Signals and Systems (ELEC 221)",
        "Partial Differential Equations (MATH 257)",
      ],
    },
  ],
};
