export const siteConfig = {
  name: "Ella Majkic",
  title: "UBC Engineering Physics Student",
  description: "Portfolio website of Ella Majkic",
  accentColor: "#5E35B1",
  social: {
    email: "ellamaj8@gmail.com",
    linkedin: "https://www.linkedin.com/in/ella-majkic-951527289/",
    github: "https://github.com/emajkic",
  },
  aboutMe1: "Hi! My name is Ella Majkic. I am a 3rd year Engineering Physics Student at the University of British Columbia pursuing a minor in Honours Mathematics. My interests include applied mathematics, software development, machine learning, and physics.",
  aboutMe2: "Engineering Physics is a degree which combines the disciplines of electrical engineering, software engineering, mechanical engineering, and pure math and physics. It offers a broad range of hands-on engineering experiences while also providing a strong foundation in advanced physics and math.",
  skills: ["Git", "Python", "Java", "C++", "Linux", "KiCAD", "ROOT", "ROS", "MATLAB"],
  projects: [
    {
      img1: "/robot1.png",
      img2: "/robot2.jpg",
      img3: "/robot3.jpg",
      slug: "robot-project",
      name: "Autonomous Competition Robot",
      description:
        "Designed, prototyped, and built an autonomous robot to participate in Engineering Physics 253 course competition.",
      skills: ["Circuit Design", "C++", "Soldering", "Software Design", "Prototyping"],
    },
    {
      img1: "/ml1.jpg",
      img2: "/ml2.png",
      img3: "/ml3.jpg",
      slug: "machine-learning-project",
      name: "ROS Machine Learning Project",
      description:
        "(In Progress) Programming robot in simulated Gazebo environment for ENPH 353 project/competition course using recent machine learning and computer vision techniques.",
      skills: ["OpenCV", "ROS", "Python", "Machine Learning", "Linux Terminal"],
    },
    {
      img1: "/motor1.jpg",
      img2: "/motor3.jpg",
      img3: "/motor2.jpg",
      slug: "motor-project",
      name: "PID Motor Controller",
      description:
        "Built a circuit capable of setting and actively controlling the speed of an electric motor using PI control.",
      skills: ["Circuitry", "Electrical Design", "Prototyping"],
    },
    {
      img1: "/java1.png",
      img2: "/java2.png",
      img3: "/java3.png",
      slug: "java-project",
      name: "Java Tic-Tac-Toe GUI Game",
      description:
        "Programmed an interactive tic-tac-toe GUI game using Java.",
      skills: ["Java", "Object Oriented Programming", "GUI design"],
    },
    
    //add ROS ENPH353 project
    
  ],
  experience: [
    {
      slug: "triumf-experience",
      company: "TRIUMF Particle Accelerator",
      position: "Student Research Assistant - PIONEER Experiment",
      dateRange: "Jan 2025 - May 2025",
      description: "Worked with Purity Monitor Assembly (PUMA) instrument for high-precision rare pion decay experiment, PIONEER. Developed physics simulations with C++ and Python; designed vacuum system for PUMA testing. [Click for more]",
      pdf1: "/final_poster.pdf",
      pdf2: "/final_report.pdf",
      para1: "During my time at TRIUMF, I worked with the PIONEER group on a rare pion decay experiment. The PIONEER experiment will be conducted in a large liquid xenon (LXe) calorimeter, and continuous monitoring of the LXe's purity is required during the experiment. To achieve this, I was involved in the development of a Purity Monitor Assembly (PUMA) and its calibration device to be used in high-precision experiments with LXe calorimeters.",
      para2: "I conducted physics simulations of PUMA to better understand particle behaviour inside the assembly in various media. I used COMSOL Multiphysics to perform electrostatic finite element analysis on the CAD model of PUMA. I also wrote C++ scripts in Linux using Garfield++, a library written by CERN for detailed simulation of particle detectors. Some results are shown below.",
      img1_1: "/sim1.png",
      img1_2: "/sim2.png",
      img1_3: "/sim3.jpg",
      para3: "Further, I designed and built a vacuum system to perform initial tests of the calibration device for PUMA. This involved the mechanical design and assembly of components, integration of the calibration device for PUMA into the system, and troubleshooting iterations to reach our desired pressure of 1e-6 bar. I also designed an electrical box for easy interfacing with the pressure gauge I chose for the system.",
      img2_1: "/vac1.jpg",
      img2_2: "/vac2.jpg",
      img2_3: "/vac3.jpg",
      para4: "After ensuring the vacuum system could reliably reach low pressures over extended periods of time, I began testing PUMA's calibration device inside the vacuum system. I collected data under various electric potential configurations inside the assembly. Later, we pumped gaseous argon into the vacuum system and continued tests in the new medium.",
      img3_1: "/test1.jpg",
      img3_2: "/test2.png",
      img3_3: "/test3.jpg",
      para5: "Working at TRIUMF was a great experience and I enjoyed being in charge of a project within a larger cutting-edge physics context. I got to experience both self-led work and collaboration with a team.",
      para6: "At the end of my term, I participated in TRIUMF's co-op poster session. I created a poster (shown below) to summarize the work I did. I was honoured to be awarded 2nd place out of all co-ops!",
      para7: "Below is the full report I wrote about my co-op term. It provides more details about my time at TRIUMF.",
      bullets: [
        "Worked on Purity Monitor Assembly (PUMA) instrument for a rare pion decay experiment (PIONEER)",
        "Developed physics simulations of particle behaviour in PUMA",
        "Designed and assembled a vacuum system for PUMA testing",
      ],
    },
    {
      slug: "opbots-experience",
      company: "UBC Open Robotics Design Team",
      position: "Software Engineer, Navigation Subteam",
      dateRange: "Sept 2023 - May 2025",
      description: "Programmed autonomous navigation of service robot for international RoboCup@Home competition - used ROS in Linux to write Python scripts. [Click for more]",
      para1: "UBC Open Robotics is a student design team working on several advanced robotics projects. I was part of the Software Subteam working on the RoboCup@Home project. RoboCup@Home is an international competition where teams develop autonomous home service robots to help those with domestic assistance needs. Robots must be capable of human-robot interaction, navigation in dynamic environments, object recognition and manipulation, and more.",
      para2: "While working on the navigation side of the software for our robot, I developed ROS (Robot Operating System) Python scripts to allow the robot to navigate new, dynamic environments. This meant integrating various sensors with software and developing communication protocols for the robot's subsystems. All ROS development was done on Linux (Ubuntu 20.04). I also performed research and analysis of LIDAR sensors and SLAM (Simultaneous Localization and Mapping) frameworks for use in the robot.",
      img1_1: "/ros2.jpg",
      img1_2: "/ros3.png",
      img1_3: "/ros1.jpg",
      para3: "Further, during my first few months after joining Open Robotics, I performed mechanical onboarding for the team. This included designing a chassis for a simple robot using OnShape CAD and 3D printing various mechanical components. During this time, During this time, I gained hands-on experience with mechanical design and robotics practices used in industry.",
      img2_1: "/chass1.jpg",
      img2_2: "/chass2.jpg",
      img2_3: "/chass3.jpg",
      bullets: [
        "Developed Python scripts to program autonomous navigation of service robot for international RoboCup@Home competition",
        "Worked with ROS (Robot Operating System) in Linux Ubuntu 20.04 distribution",
        "Collaborated with large student team to achieve project goals",
      ],
    }, 
  ],
  education: [
    {
      school: "University of British Columbia",
      degree: "Bachelor of Applied Science in Engineering Physics",
      dateRange: "2023 - 2028",
      achievements: [
        "2023-2025: Dean's Scholar, Dean's List",
        "2024: Trek Excellence Scholarship",
      ],
      courses: "Relevant courses I have completed include Data Structures and Algorithms, Linear Circuits, ",
    },
  ],
};
